# CatSero Plugin Config
# Generate by CatSero v@plugin.version@

# 语言文件
locale: zh_CN

# bStats
bstats: true

# 检查更新
check-update:
  # 是否启用
  enable: true
  # 检查更新间隔
  # 单位: 秒
  interval: 3600
  # 版本模式
  mode: latest
  # 检查更新服务器API地址，一般情况请勿修改
  api-url: https://mcp.huahuo-cn.tk/api/CatSero/version

# 自定义QQ命令头
custom-qq-command-prefix:
  # 是否启用
  enable: false
  # 命令头
  prefix: ""
