# CatSero配置文件

# 语言文件
locale: zh_CN
# 接受bStats统计(https://bstats.org)
allow-bstats: true
# 接受插件启动时的警告
allow-start-warn: true
# 检查更新功能
check-update:
  # 启用
  enabled: true
  # 版本(开发版 -> dev || 正式版 -> passed)
  version: passed
  # 启动时覆盖旧的zh_CN.lang I18n文件
  auto-zh: false

# QQ机器人相关设置
qq-set:
  # 使用的群
  group: 123456
  # 使用的机器人
  bot: 123456
  # 拥有QQ权限的用户
  qq-op: 123456

# 通用格式
format-list:
  # 插件消息前缀
  prefix:
    to-mc: "&e[&bCatSero&e]"
    to-qq: "[CatSero]"
  # 自定义Q群命令头
  custom-command-head:
    # 启用此功能
    enabled: false
    # 前缀
    prefix: ""