# CatSero配置文件

# 接受bStats统计
allow-bstats: true
# 接受插件启动时的警告
allow-start-warn: true
# 检查更新功能
check-update:
  # 启用
  enabled: true
  # 版本(开发版 -> dev || 正式版 -> passed)
  version: passed

# 通用格式
format-list:
  # 插件消息前缀
  prefix:
    to-mc: "&e[&bCatSero&e]"
    to-qq: "[CatSero]"
  # Console名称
  console-name: "控制台"