name: CatSero
main: moe.xmcn.catsero.Main
version: 1.0-pre1
author: XiaMoHuaHuo_CN
depend:
  - MiraiMC
commands:
  catsero:
    description: "CatSero 基础方法"
    permission: catsero.admin
    permission-message: "你没有权限执行该命令"
permissions:
  catsero.*:
    description: "CatSero 权限组"
    default: op
    children:
      - catsero.admin