name: CatSero
main: moe.xmcn.catsero.Main
version: ${project.version}
api-version: 1.13
author: XiaMoHuaHuo_CN
depend:
  - MiraiMC
commands:
  catsero:
    description: "CatSero 基础方法"
    permission-message: "你没有权限执行该命令"
  csm:
    description: "CatSero 发消息到QQ群"
permissions:
  catsero.admin:
    description: "CatSero OP权限组"
    default: op
