name: CatSero
main: moe.xmcn.catsero.Main
description: 基于MiraiMC的Minecraft功能插件
version: ${project.version}
api-version: 1.13
author: XiaMoHuaHuo_CN
softdepend:
  - MiraiMC
  - PlaceholderAPI
commands:
  catsero:
    description: "CatSero 基础方法"
  cms:
    description: "CatSero 发消息到QQ群"
permissions:
  catsero.*:
    description: "CatSero所有权限组"
    default: false
    children:
      catsero.admin:
        description: "CatSero OP权限组"
        default: op
      catsero.send-player-join-quit:
        description: "玩家加入/退出游戏转发权限"
        default: false
        children:
          catsero.send-player-join-quit.join:
            description: "玩家加入游戏转发权限"
            default: op
          catsero.send-player-join-quit.quit:
            description: "玩家退出游戏转发权限"
            default: op
