# CatSero功能设置

# PingHost功能
pinghost:
  # 启用此功能
  enabled: false
  # 仅OP可用
  op-only: false

# 天气获取功能
weatherinfo:
  # 启用此功能
  enabled: false

# QMsg功能
qmsg:

  # 发送玩家加入/退出消息
  send-player-join-quit:
    # 启用此功能
    enabled: false
    # 格式
    format:
      join: ""
      quit: ""
  
  forward-chat:
    # 启用此功能
    enabled: false
    # 格式
    format:
      to-mc: ""
      to-qq: ""
    prefix:
      # 启用此功能
      enabled: false
      format:
        to-mc: "#"
        to-qq: "#"

whitelist:
  # 启用此功能
  enabled: false
  # QQ自助申请
  ass:
    # 启用此功能
    enabled: false
    # 格式
    format: "申请白名单 %playername%"
