# CatSero功能设置

# PingHost功能
pinghost:
  # 启用此功能
  enabled: false
  # 仅OP可用
  op-only: false

# 天气获取功能
weatherinfo:
  # 启用此功能
  enabled: false

qbanplayer:
  # 启用此功能
  enabled: false

# QMsg功能
qmsg:

  # 发送玩家加入/退出消息
  send-player-join-quit:
    # 启用此功能
    enabled: false
    # 格式
    format:
      join: "%player%加入了游戏"
      quit: "%player%退出了游戏"
  
  # 转发MC-QQ聊天
  forward-chat:
    # 启用此功能
    enabled: false
    # 格式
    format:
      to-mc: ""
      to-qq: ""
    prefix:
      # 启用此功能
      enabled: false
      format:
        to-mc: "#"
        to-qq: "#"

# 白名单功能
whitelist:
  # 启用此功能
  enabled: false
  # QQ自助申请
  ass:
    # 启用此功能
    enabled: false
    # 格式
    format: "申请白名单 %player%"

# 玩家加入/退出游戏消息
join-quit-message:
  # 启用此功能
  enabled: false
  # 格式
  format:
    join: ""
    quit: ""

# 新人加群欢迎
group-member-change-message:
  enabled: false
  format:
    join: "欢迎%at%(%code%)\n加入了本群！"
    quit: ""
