# CatSero功能设置

# PingHost功能
pinghost:
  # 启用此功能
  enabled: false
  op-only: false

# 天气获取功能
weatherinfo:
  # 启用此功能
  enabled: false

# QMsg功能
qmsg:

  send-player-join-quit:
    # 启用此功能
    enabled: false
    format:
      join: ""
      quit: ""
  
  forward-chat:
    # 启用此功能
    enabled: false
    format:
      to-mc: ""
      to-qq: ""
    prefix:
      # 启用此功能
      enabled: false
      format:
        to-mc: "#"
        to-qq: "#"
