# CatSero功能设置

# 发送玩家加入/退出消息
send-player-join-quit:
  enabled: false
  var:
    bot: example
    group: example
  format:
    join: "%player%加入了游戏"
    quit: "%player%退出了游戏"
  need-permission: false

# 聊天转发
chat-forward:
  enabled: false
  var:
    bot: example
    group: example
  format:
    to-mc: |-
      &e[&aQQ&e]&r%name%(%code%):
      %message%
    to-qq: |-
      [MC]%player%:
      %message%
  clean-colorcode: true
  filter:
    enabled: false
    list:
      - "傻逼"
      - "fuck"
    replace-only: false
  prefix:
    enabled: false
    format:
      to-mc: "#"
      to-qq: "#"

# 发送玩家死亡消息
send-player-death:
  enabled: false
  var:
    bot: example
    group: example
  format: "%player%死了,因为\n%deathmes%"

# 新人加入群欢迎
new-group-member-message:
  enabled: false
  var:
    bot: example
    group: example
  format: "欢迎%at%（%code%）加入本群!"

# TPS获取
get-tps:
  enabled: false
  var:
    bot: example
    group: example

# 在线玩家获取
get-online-players:
  enabled: false
  var:
    bot: example
    group: example
  format: |-
    当前在线: %count%
    最大在线: %max%
    玩家列表: %list%

# 玩家管理器
player-manager:
  enabled: false
  var:
    bot: example
    group: example
  tools:
    - ban
    - op
    - kick
  configs:
    ban-tool:
      ban:
        default-reason: "你已被此服务器封禁"
        custom-command:
          enabled: false
          command: "ban %player% %reason%"
      unban:
        custom-command:
          enabled: false
          command: "pardon %player%"
    kick-tool:
      kick:
        default-reason: "你已被踢出"

# QQ群执行Minecraft命令
# 正在实验
dispatch-command:
  enabled: false
  var:
    bot: example
    group: example
