# CatSero UsesConfig
# Generate by CatSero v@plugin.version@

# 发送玩家加入/退出消息
send-player-join-quit:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # - %player% 加入玩家名称
  format:
    # 加入
    join: "%player%加入了游戏"
    # 退出
    quit: "%player%退出了游戏"
  # 需要拥有权限才会发送
  need-permission: false

# 聊天转发
chat-forward:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # - %name%  (To MC)发送者名称
  # - %code%  (To MC)发送者QQ号
  # - %message%  消息内容
  # - %player%  (To QQ)发送玩家名称
  # - %channel%  (To QQ | TrChat Only)聊天频道ID
  format:
    # 发送到Minecraft
    to-mc: |-
      &e[&aQQ&e]&r%name%(%code%):
      %message%
    # 发送到QQ
    to-qq: |-
      [MC]%player%:
      %message%
  # 清理消息中的格式代码
  clean-colorcode: true
  # 关键词检测
  filter:
    # 功能开关
    # true | false
    enable: false
    # 关键词列表
    list:
      - "傻逼"
      - "fuck"
    # 只将关键词变为"***"而不是取消该条消息的转发
    # true | false
    replace-only: false
  # 聊天前缀
  prefix:
    # 功能开关
    # true | false
    enable: false
    # 格式
    format:
      # 发送到Minecraft
      to-mc: "#"
      # 发送到QQ
      to-qq: "#"

# 发送玩家死亡消息
send-player-death:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # - %player%  玩家名
  # - %deathmes%  死亡消息
  format: "%player%死了,因为\n%deathmes%"

# 新人加入群欢迎
new-group-member-message:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # - %at%  @新成员
  # - %code%  新成员QQ号
  format: "欢迎%at%（%code%）加入本群!"

# TPS获取
get-tps:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group

# 在线玩家获取
get-online-players:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # - %count%  当前在线玩家数
  # - %max%  最大在线玩家数
  # - %list%  当前在线玩家列表
  format: |-
    当前在线: %count%
    最大在线: %max%
    玩家列表: %list%

# 玩家管理器
player-manager:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 启用的工具
  # 支持：ban, op, kick
  tools:
    - ban
    - op
    - kick
  # 子功能配置
  configs:
    # Ban工具
    ban-tool:
      # Ban命令
      ban:
        # 默认原因
        default-reason: "你已被此服务器封禁"
        # 使用自定义命令而不是Bukkit内置封禁
        custom-command:
          # 功能开关
          # true | false
          enable: false
          # 封禁命令
          # 内置占位符:
          # - %player%  玩家名
          # - %reason%  原因
          command: "ban %player% %reason%"
      # UnBan命令
      unban:
        # 使用自定义命令而不是Bukkit内置封禁
        custom-command:
          # 功能开关
          # true | false
          enable: false
          # 封禁命令
          # 内置占位符:
          # - %player%  玩家名
          command: "pardon %player%"
    # Kick工具
    kick-tool:
      # Kick命令
      kick:
        # 默认原因
        default-reason: "你已被踢出"

# QQ群执行Minecraft命令
# 正在实验
dispatch-command:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
