# CatSero功能设置

# PingHost功能
pinghost:
  # 启用此功能
  enabled: false
  # 仅OP可用
  op-only: false

# 天气获取功能
weatherinfo:
  # 启用此功能
  enabled: false

# QQ封禁玩家
qban-player:
  # 启用此功能
  enabled: false

# QQ踢出玩家
qkick-player:
  # 启用此功能
  enabled: false

# QQ给玩家OP
qop-player:
  # 启用此功能
  enabled: false

# QMsg功能集
qmsg:

  # 发送玩家加入/退出消息
  send-player-join-quit:
    # 启用此功能
    enabled: false
    # 格式
    format:
      join: "%player%加入了游戏"
      quit: "%player%退出了游戏"
  
  # 转发MC-QQ聊天
  forward-chat:
    # 启用此功能
    enabled: false
    # 格式
    format:
      to-mc: "[%time%][QQ][%groupname%(%groupcode%)]%sendername%(%sendercode%):\n%message%"
      to-qq: "[MC]%player%:\n%message%"
    prefix:
      # 启用此功能
      enabled: false
      # 格式(只支持单个，字符，请勿输入多个)
      format:
        to-mc: "#"
        to-qq: "#"
    # 发到QQ自动清理消息中的颜色代码
    clean-colorcode: true

# 玩家加入/退出游戏消息
join-quit-message:
  # 启用此功能
  enabled: false
  # 格式
  format:
    join: "[&a+&r]&e%playser%"
    quit: "[&c-&r]&e%playser%"

# 新人加群欢迎
new-group-member-message:
  enabled: false
  format: "欢迎%at%(%code%)\n加入了本群！"
