# CatSero功能设置

# PingHost功能
pinghost:
  # 启用此功能
  enabled: false
  # 需要权限
  need-permission: false

# 天气获取功能
weatherinfo:
  # 启用此功能
  enabled: false
  # 需要权限
  need-permission: false

# QQ封禁玩家
qban-player:
  # 启用此功能
  enabled: false
  # 封禁理由
  reason: "你已被此服务器封禁"
  # 使用数据库而不是原版封禁
  use-database: true

# QQ踢出玩家
qkick-player:
  # 启用此功能
  enabled: false

# QQ给玩家OP
qop-player:
  # 启用此功能
  enabled: false

# 发送玩家加入/退出消息
send-player-join-quit:
  # 启用此功能
  enabled: false
  # 格式
  format:
    join: "%player%加入了游戏"
    quit: "%player%退出了游戏"
  # 是否需要权限
  need-permission: false

# 转发MC-QQ聊天
forward-chat:
  # 启用此功能
  enabled: false
  # 格式(若安装TrChat请在extra-configs/trchat.yml配置Minecraft转发QQ格式)
  format:
    to-mc: "[%time%][QQ][%groupname%(%groupcode%)]%sendername%(%sendercode%):\n%message%"
    to-qq: "[MC]%player%:\n%message%"
  # 聊天转发前缀
  prefix:
    # 启用此功能
    enabled: false
    # 格式
    format:
      to-mc: "#"
      to-qq: "#"
  # 发到QQ自动清理消息中的颜色代码
  clean-colorcode: true
  # 使用MiraiMC内置绑定
  use-bind: false

# 新人加群欢迎
new-group-member-message:
  # 启用此功能
  enabled: false
  # 格式
  format: "欢迎%at%(%code%)\n加入了本群！"

# PunyCode功能
punycode:
  # 启用此功能
  enabled: false
  # 支持编码URL
  url-support: false

# 获取TPS功能
get-tps:
  # 启用此功能
  enabled: false

# 绑定QQ功能
bind-qq:
  # 启用此功能
  enabled: false

# QQ执行Minecraft命令
# （限于不调用NMS，无法显示执行日志）
qdispatch-command:
  # 启用此功能
  enabled: false