# CatSero UsesConfig
# Generate by CatSero v@plugin.version@

# 发送玩家加入/退出消息
send-player-join-quit:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # - %player% 加入玩家名称
  format:
    # 加入
    join: "%player%加入了游戏"
    # 退出
    quit: "%player%退出了游戏"
  # 需要拥有权限才会发送
  need-permission: false

# 发送玩家死亡消息
send-player-death:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # - %player%  玩家名
  # - %message%  死亡消息
  format: "%player%死了,因为\n%message%"
  # 需要拥有权限才会发送
  need-permission: false

# 新人加入群欢迎
new-group-member-message:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # - %at%  @新成员
  # - %code%  新成员QQ号
  format: "欢迎%at%（%code%）加入本群!"

# 玩家解锁进度转发
send-advancement:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # = %player%  玩家名
  # - %name%  进度名
  # - %description%  进度描述
  format: "%player%达成了进度: %name%\n描述: %description%"

# TPS获取
get-tps:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group

# 在线玩家获取
get-online-players:
  # 功能开关
  # true | false
  enable: false
  # Bot & Group设置
  var:
    # BotID
    bot: hello-bot
    # GroupID
    group: hello-group
  # 格式
  # 内置占位符:
  # - %count%  当前在线玩家数
  # - %max%  最大在线玩家数
  # - %list%  当前在线玩家列表
  format: |-
    当前在线: %count%
    最大在线: %max%
    玩家列表: %list%
