name: 问题报告
description: "如果你想反馈 Bug，请使用此模板。"
labels: ["漏洞"]
body:
  - type: textarea
    id: description
    attributes: 
      label: 问题描述
      description: 在下方的编辑框描述你的问题
      placeholder: 请尽可能说明你遇到的问题，包括你是如何使用插件的，配置文件有没有调过等等
    validations:
      required: true
  - type: textarea
    id: recurrent
    attributes: 
      label: 复现方法
      description: 在下方的编辑框描述如何触发这个漏洞（分步需换行请直接回车，会为你添加标号）
      placeholder: 能看到这个？说明你没有看描述，请自己加上“1. ”
      value: "1. "
    validations:
      required: true
  - type: dropdown
    id: servertype
    attributes: 
      label: 服务端类型
      description: 选择你正在使用的服务端类型
      options: 
        - Bukkit
        - BungeeCord
        - Sponge
        - Velocity
        - Nukkit
    validations:
      required: true
  - type: input
    id: serverversion
    attributes:
      label: 服务端版本
      description: 填写你正在使用的服务端版本，例如 Paper-1.12.2
      placeholder: 在服务端输入 /ver 查看版本
    validations:
      required: true
  - type: input
    id: pluginversion
    attributes:
      label: MiraiMC 插件版本
      description: 填写你正在使用的 MiraiMC 版本
      placeholder: 在服务端输入 /miraimc 查看版本
    validations:
      required: true
  - type: textarea
    id: serverlog
    attributes: 
      label: 服务端日志
      description: 在下方复制你的服务端日志
      placeholder: 请提供完整的服务端日志，自以为知道问题所在而仅提供一两行将被直接关闭。
      render: text
    validations:
      required: true
  - type: textarea
    id: extra
    attributes: 
      label: 额外说明
      description: 还有什么要补充的吗？
      placeholder: |
        提示：
        你可以提供系统环境、Java版本、你使用了什么依赖MiraiMC的插件、重置插件配置后问题是否仍然存在、你使用的插件列表
        你还可以提供截图和文件（直接拖动文件到编辑框）
