name: Java CI with Maven - Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Refactor Version Env
        run: sed -i "s/\${project.version}/1.1-pre3/g" `grep 1.1-pre3 -rl /`

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload a Build Target
        uses: actions/upload-artifact@v2.3.1
        with:
          name: "CatSero-Artifact"
          path: target/
