name: Java CI with Maven - Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@latest
        with:
          java-version: '8'
          distribution: 'zulu'
      - name: Build with Maven
        run: mvn package

      - name: Upload Build Target
        uses: actions/upload-artifact@latest
        with:
          name: "CatSero-Artifact"
          path: target/

      - name: Upload Build JAR
        uses: actions/upload-artifact@latest
        with:
          name: "CatSero-JAR"
          path: target/CatSero-*.jar
