name: Java CI with Maven - Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Rename Artifact
      run: cd target/ && mv CatSero.jar CatSero-SNAPSHOT.jar
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "CatSero-SNAPSHOT.jar"
        path: target/CatSero-SNAPSHOT.jar
